sudo: enable
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
branches:
  only:
    - deploy
script:
 - chmod +x ./deploy.sh
 - ./deploy.sh

notifications:
  slack: 
    rooms:
      - jweboytm:woLS6D9oasTaWyC1Ks4zqCne
    on_success: change
    on_failure: always
    on_pull_requests: false